# Generated by Django 5.0.3 on 2024-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='release_date',
            field=models.CharField(default='lol', max_length=50),
            preserve_default=False,
        ),
    ]
